### ISSUE TITLE
Weird issue when calling yarn install

### ISSUE THREAD

**Issue by JacobInCode** [dylsteck/litecast#11]
this is quite possibly an issue on my end but any help much appreciated 
![image](https://github.com/dylsteck/litecast/assets/24348787/11053d59-4dc6-444e-8472-4e7612c508fb)

**Comment by JacobInCode** [comment]
in the console the error is with typesync and saying it can't parse "*"

**Comment by dylsteck** [comment]
Closing for now since the codebase has changed quite a bit since this issue, but happy to hop on and debug if you're still having trouble running the app locally @StringTheory69
